<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Ardalis.Specification" Version="9.3.1" />
        <PackageReference Include="Ardalis.Specification.EntityFrameworkCore" Version="9.3.1" />
        <PackageReference Include="FluentValidation" Version="12.1.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.23" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.21" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />

        <!-- Для работы с Include нужен этот пакет -->
        <!-- Entity Framework Core -->
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.23" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        
        <!-- PostgreSQL -->
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.10" />
        <PackageReference Include="Testcontainers.PostgreSql" Version="4.10.0" />

        <!-- EF Core Tools для миграций -->
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.10">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <!-- Если используется In-Memory база -->
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.23" />

        <!-- Serilog -->
        <PackageReference Include="Serilog.AspNetCore" Version="8.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="5.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
        
        <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.1" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="BookLibrary.Tests" />
    </ItemGroup>

</Project>
