// <auto-generated />
using System;
using BookLibrary.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookLibrary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217074602_UpdateBookSeedData")]
    partial class UpdateBookSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookLibrary.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DeathYear")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(8850),
                            IsActive = true,
                            Name = "Агата Кристи",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(8851)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(8854),
                            IsActive = true,
                            Name = "Артур Конан Дойл",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(8854)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(8856),
                            IsActive = true,
                            Name = "Джоан Роулинг",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(8857)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(8858),
                            IsActive = true,
                            Name = "Фёдор Достоевский",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(8858)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(8860),
                            IsActive = true,
                            Name = "Лев Толстой",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(8860)
                        });
                });

            modelBuilder.Entity("BookLibrary.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Genre")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Isbn");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.HasIndex("Title");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9251),
                            Genre = "Детектив",
                            ISBN = "978-5-17-101234-5",
                            IsAvailable = true,
                            PublicationYear = 1939,
                            Title = "Десять негритят",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9252)
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9257),
                            Genre = "Детектив",
                            ISBN = "978-5-17-101235-2",
                            IsAvailable = true,
                            PublicationYear = 1934,
                            Title = "Убийство в Восточном экспрессе",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9258)
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9261),
                            Genre = "Фэнтези",
                            ISBN = "978-5-17-112345-6",
                            IsAvailable = true,
                            PublicationYear = 1997,
                            Title = "Гарри Поттер и философский камень",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9261)
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9264),
                            Genre = "Роман",
                            ISBN = "978-5-699-12345-6",
                            IsAvailable = true,
                            PublicationYear = 1866,
                            Title = "Преступление и наказание",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9264)
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9266),
                            Genre = "Роман",
                            ISBN = "978-5-699-23456-7",
                            IsAvailable = true,
                            PublicationYear = 1869,
                            Title = "Война и мир",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9267)
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9269),
                            Genre = "Детектив",
                            ISBN = "978-5-699-34567-8",
                            IsAvailable = true,
                            PublicationYear = 1902,
                            Title = "Шерлок Холмс: Сокращенное издание",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9269)
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9272),
                            Genre = "Антиутопия",
                            ISBN = "978-5-17-999999-9",
                            IsAvailable = true,
                            PublicationYear = 1949,
                            Title = "Идиот",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9272)
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9274),
                            Genre = "Фантастика",
                            ISBN = "978-5-17-888888-8",
                            IsAvailable = true,
                            PublicationYear = 1965,
                            Title = "Бесы",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9274)
                        });
                });

            modelBuilder.Entity("BookLibrary.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9131),
                            Name = "Детектив",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9131)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9137),
                            Name = "Фэнтези",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9137)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9139),
                            Name = "Классика",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9140)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9141),
                            Name = "Научная фантастика",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9142)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9143),
                            Name = "Роман",
                            UpdatedAt = new DateTime(2026, 2, 17, 7, 46, 1, 719, DateTimeKind.Utc).AddTicks(9143)
                        });
                });

            modelBuilder.Entity("BookLibrary.Models.Book", b =>
                {
                    b.HasOne("BookLibrary.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookLibrary.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookLibrary.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookLibrary.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
